apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql 
  namespace: sandbox 
  labels:
    k8s-app: mysql 
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mysql 
  template:
    metadata:
      labels:
        k8s-app: mysql 
    spec:
      containers:
      - name: mysql 
        image: mysql:5.7.18
        env:
        - name: MYSQL_ROOT_PASSWORD 
          value: 72b154cb 
        ports:
        - containerPort: 3306 
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          readOnly: false
        - name: conf
          mountPath: /etc/mysql/mysql.conf.d
          readOnly: false
      volumes:
      - name: data
        nfs:
          server: 127.0.0.1
          path: /opt/mysql/data/
      - name: conf
        nfs:
          server: 127.0.0.1
          path: /opt/mysql/conf/
      nodeSelector:
        node: sandbox 

