apiVersion: v1
kind: ReplicationController 
metadata:
  name: sandbox-mysql 
  namespace: sandbox
spec:
  replicas: 1
  selector:
    app: sandbox-mysql 
  template:
    metadata:
      labels:
        app: sandbox-mysql 
    spec:
      containers:
      - name: sandbox-mysql 
        image: mysql:5.7.18
        env:
        - name: MYSQL_ROOT_PASSWORD 
          value: 72b154cb 
        ports:
          - name: default
            containerPort: 3306 
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          readOnly: false
        - name: conf
          mountPath: /etc/mysql/mysql.conf.d
          readOnly: false
      volumes:
      - name: data
        nfs:
          server: 127.0.0.1
          path: /opt/mysql/data/
      - name: conf
        nfs:
          server: 127.0.0.1
          path: /opt/mysql/conf/
      nodeSelector:
        node: sandbox 
